# -*- coding: utf-8 -*-
"""CSI 661 Midterm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5eO2x5t4Ol3w5wz2pYLmgLE4StJWmcI

Download the Dataset
"""

!wget -q https://files.grouplens.org/datasets/movielens/ml-1m.zip
!unzip -q ml-1m.zip
print("Dataset ready!")

"""Load the Data"""

import pandas as pd
import numpy as np

# Load ratings (who rated what and how much)
ratings = pd.read_csv('ml-1m/ratings.dat', sep='::',
                      names=['user_id', 'movie_id', 'rating', 'timestamp'],
                      engine='python')

# Load users (who they are, including gender)
users = pd.read_csv('ml-1m/users.dat', sep='::',
                    names=['user_id', 'gender', 'age', 'occupation', 'zip'],
                    engine='python')

print("Ratings shape:", ratings.shape)
print("Users shape:", users.shape)
print(users.head())

"""Prepare the Data"""

from sklearn.model_selection import train_test_split

# Create safe ID mappings (converts user_id and movie_id to 0,1,2,3...)
all_user_ids = sorted(ratings['user_id'].unique())
all_movie_ids = sorted(ratings['movie_id'].unique())

user2idx = {u: i for i, u in enumerate(all_user_ids)}
movie2idx = {m: i for i, m in enumerate(all_movie_ids)}

ratings['user_idx'] = ratings['user_id'].map(user2idx)
ratings['movie_idx'] = ratings['movie_id'].map(movie2idx)

n_users = len(all_user_ids)
n_movies = len(all_movie_ids)
print(f"Total users: {n_users}, Total movies: {n_movies}")

# Attacker-only split: MF does NOT use this to filter ratings
train_users, test_users = train_test_split(
    all_user_ids, test_size=0.2, random_state=42
)

print(f"Attacker train users: {len(train_users)}, test users: {len(test_users)}")

# MF trains on ALL ratings: every user gets a real learned embedding
train_data = ratings.copy()
print(f"MF training ratings: {len(train_data)}")  # should be 1000209

"""Build the MF Model"""

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# This tells PyTorch how to feed our data into the model
class RatingsDataset(Dataset):
    def __init__(self, df):
        self.users = torch.tensor(df['user_idx'].values, dtype=torch.long)
        self.movies = torch.tensor(df['movie_idx'].values, dtype=torch.long)
        self.ratings = torch.tensor(df['rating'].values, dtype=torch.float32)

    def __len__(self):
        return len(self.ratings)

    def __getitem__(self, idx):
        return self.users[idx], self.movies[idx], self.ratings[idx]

# Load data in batches of 1024 rows at a time
train_loader = DataLoader(RatingsDataset(train_data), batch_size=1024, shuffle=True)

# The actual MF model
# Each user gets a vector of 32 numbers (embedding_dim=32)
# Each movie also gets a vector of 32 numbers
# Predicted rating = dot product of user vector and movie vector
class MatrixFactorization(nn.Module):
    def __init__(self, n_users, n_movies, embedding_dim=32):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, embedding_dim)
        self.movie_emb = nn.Embedding(n_movies, embedding_dim)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.movie_emb.weight, std=0.01)

    def forward(self, user_ids, movie_ids):
        u = self.user_emb(user_ids)
        m = self.movie_emb(movie_ids)
        return (u * m).sum(dim=1)

print("Model defined successfully!")

"""Train the Model"""

model = MatrixFactorization(n_users, n_movies, embedding_dim=32)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

EPOCHS = 10
loss_history = []

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for users_batch, movies_batch, ratings_batch in train_loader:
        optimizer.zero_grad()
        preds = model(users_batch, movies_batch)
        loss = loss_fn(preds, ratings_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    loss_history.append(avg_loss)
    print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {avg_loss:.4f}")

print("Training done!")

"""Extract User Embeddings"""

model.eval()  # switch model to evaluation mode (turns off training behavior)

with torch.no_grad():  # we don't need gradients here
    all_idx = torch.arange(n_users)
    user_embeddings = model.user_emb(all_idx).numpy()

print(f"Embeddings shape: {user_embeddings.shape}")
# Should print: (6040, 32)
# meaning: 6040 users, each with 32 numbers

np.save('user_embeddings.npy', user_embeddings)
print("Saved!")

"""Prepare Embeddings for the Attacker"""

# Build a table: user_id | 32 embedding numbers | gender
emb_df = pd.DataFrame(user_embeddings)       # 32 columns of numbers
emb_df['user_id'] = all_user_ids             # add user_id column

# Add gender from the users file
emb_df = emb_df.merge(users[['user_id', 'gender']], on='user_id')

# Convert gender to numbers: F=0, M=1
gender_map = {'F': 0, 'M': 1}
emb_df['gender_label'] = emb_df['gender'].map(gender_map)

# Use the SAME split from Step 4
emb_train = emb_df[emb_df['user_id'].isin(train_users)]
emb_test  = emb_df[emb_df['user_id'].isin(test_users)]

# X = the 32 embedding numbers (input to attacker)
# y = gender label (what attacker tries to predict)
feature_cols = list(range(32))

X_train = emb_train[feature_cols].values
y_train = emb_train['gender_label'].values

X_test = emb_test[feature_cols].values
y_test = emb_test['gender_label'].values

print(f"Attacker train size: {len(X_train)}, test size: {len(X_test)}")

"""Train the Attacker & Get Results"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# Train the attacker
attacker = LogisticRegression(max_iter=1000, random_state=42)
attacker.fit(X_train, y_train)

# Make predictions on test users
y_pred = attacker.predict(X_test)
y_prob = attacker.predict_proba(X_test)[:, 1]

# Final numbers for the report
acc = accuracy_score(y_test, y_pred)
f1  = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print("=" * 35)
print("  ATTACKER RESULTS (MF Embeddings)")
print("=" * 35)
print(f"  Accuracy  : {acc:.4f}")
print(f"  F1 Score  : {f1:.4f}")
print(f"  AUC       : {auc:.4f}")
print("=" * 35)

"""Plots

"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(range(1, EPOCHS+1), loss_history, marker='o', color='steelblue')
plt.title('MF Training Loss by Epoch')
plt.xlabel('Epoch')
plt.ylabel('MSE Loss')
plt.grid(True)
plt.tight_layout()
plt.savefig('mf_loss.png')
plt.show()
print("Plot saved!")